_target_: backends.tensorflow.TensorflowBackend
name: tensorflow_xla
version: ${tensorflow_version:}
use_xla: true
eager_mode: false
experimental_compiler: false
num_threads: null
num_interops_threads: null