defaults:
  - malloc: std
  - openmp: none
  - openmp_backend: gnu
  - backend: pytorch
  - override hydra/launcher: process


hydra:
  sweep:
    dir: results/${now:%Y-%m-%d}/${now:%H-%M-%S}


model: bert-base-cased
batch_size: 1
sequence_length: 128
benchmark_duration: 5
warmup_runs: 5
device: cpu
precision: float32
num_instances: 1
num_core_per_instance: -1