defaults:
  - malloc: std
  - backend: pytorch
  - override hydra/launcher: process


hydra:
  sweep:
    dir: results/${now:%Y-%m-%d}/${now:%H-%M-%S}


benchmark_duration: 5
warmup_runs: 5
device: cpu
precision: float32